### ISSUE TITLE
`nilHalsteadMetrics()` doesn't need to be a function in module.js

### ISSUE THREAD

**Issue by jared-stilwell** [escomplex/escomplex#55]
The `nilHalsteadMetrics()` method is only called on line 289 module.js. This logic can be moved inline.

e.g.

```
...
function calculateHalsteadMetrics (data) {
  data.length = data.operators.total + data.operands.total;
  if (data.length === 0) {
    data.vocabulary = 0;
    data.difficulty = 0;
    data.volume = 0;
    data.effort = 0;
    data.time = 0;
    data.bugs = 0;
  } else {
...
```

**Comment by Thomas-P** [comment]
I disagree. 

The code is hard to understand in fact of dependencies around the whole project. It would be much cleaner to create a factory method createHalsreadMetricsObject. If you inline this, the code get much more complicated than it is. I think the better way is to refactor out the 
```TypeScript
export interface IHalstead {
    vocabulary: number;
    difficulty: number;
    volume: number;
    effort: number;
    time: number;
    bugs: number;
}


/**
 * Halstead object
 */
export class Halstead implements IHalstead{
    bugs:number;
    difficulty:number;
    effort:number;
    time:number;
    vocabulary:number;
    volume:number;

    constructor() {
        this.bugs = 0;
        this.difficulty = 0;
        this.effort = 0;
        this.time = 0;
        this.vocabulary = 0;
        this.volume = 0;
    }

    /**
     * factory method for Halstead to create a new object
     * @returns {Halstead}
     */
    static createObject(): Halstead {
        return new Halstead();
    }
}

```
I must be extend by the other attributes, but should give a quick look to make it more understandable.

**Comment by jared-stilwell** [comment]
@Thomas-P I just saw this after leaving a comment on your other PR. Your point is taken that we should instead be constructing the metrics to default to 0. I'm willing to retract this issue and my insistence that this should be inlined in favor of a more well-formed set of defaults for the halstead metrics.

However, while the notions of classes, interfaces, and factories have become commonplace in other languages and their respective development communities, this is not the case for JavaScript. Consequently, a more idiomatic implementation of this would likely be simply to have a function which returns an object literal containing the default values for each metric.

**Comment by Thomas-P** [comment]
@jared-stilwell Hi, that is code of my implementation reversed from this repo. I use TypeScript for implementation, but think that it also works with javascript. Instead of using an raw object it could be useful to generate an object from an function by calling them with new. The goal could be to encapsulate the metric calculation to the Halstead object.

```JavaScript
function Halstead() {
    if (this instanceof Halstead === false) {
        return new Halstead();
    }
    this.bugs = 0;
    this.difficulty = 0;
    this.effort = 0;
    this.time = 0;
    this.vocabulary = 0;
    this.volume = 0;
}

Halstead.prototype = Halstead.prototype || {};

Halstead.prototype.calculateHalsteadMetrics = function () {
    this.length = this.operators.total + this.operands.total;
    if (this.length === 0) {
        return;
    }
    this.vocabulary = this.operators.distinct + this.operands.distinct;
    this.difficulty =
        (this.operators.distinct / 2) *
        (this.operands.distinct === 0 ? 1 : this.operands.total / this.operands.distinct);
    this.volume = this.length * (Math.log(this.vocabulary) / Math.log(2));
    this.effort = this.difficulty * this.volume;
    this.bugs = this.volume / 3000;
    this.time = this.effort / 18;
};
```
//@seealso: https://github.com/Thomas-P/plato-complex/blob/demo-time/lib/analyser/halstead/halstead.class.ts

I think building objects with prototype makes the code more understandable. This could be also a benefit, for understanding the code pathes. It tooks me a while to know what happened in the syntax definition methods. i hope you could understand what i mean.

**Comment by jared-stilwell** [comment]
@Thomas-P I landed a set of changes that was heavily influenced by your recommendations. The insight and thoroughness of your input is much appreciated. Thanks! ✨
