### ISSUE TITLE
Error: Cannot find module 'esprima'

### ISSUE THREAD

**Issue by pabloalmunia** [escomplex/escomplex#67]
Into index.js is used esprima (line 5):

`
var esprima = require('esprima');
`

But this package is installed only as devDependencies on package.json:

`
  "devDependencies": {
    "chai": "^3.4.1",
    "eslint": "^2.2.0",
    "esprima": "^2.7.1",
    "mocha": "^2.3.4",
    "mockery": "1.4.x",
    "sinon": "^1.16.1",
    "spooks": "0.5.x"
  },
`

As a result, the escomplex package cannot be use with a simple:

`
npm install escompex
`

**Comment by jared-stilwell** [comment]
This is resolved in PR #180
