### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by jared-stilwell** [escomplex/escomplex#85]
This repository is now unmaintained. If you are interested in assuming maintainership, please comment on this issue or email me directly.

**Comment by the-simian** [comment]
Hey - I am interested, I am trying to port Plato (or something like it) to es6, so maybe I can help a little. https://www.npmjs.com/package/es6-plato

**Comment by adam-moss** [comment]
I Jared, I may be interested in undertaking this task 👍

**Comment by adam-moss** [comment]
Hi Jared,

Do this mean you're continuing to maintain this repo ? 😃

**Comment by jared-stilwell** [comment]
Indeed. Recently had the itch to hack on this again and have had the benefit of getting some space away for a while. Was hesitant at first to remove the "unmaintained" from the project title at first, but after landing the significant refactor to the syntax modules, the path forward is quite a bit clearer.

**Comment by adam-moss** [comment]
Nice one 👍 
Do shout up if you need any assistance

**Comment by aberaud** [comment]
Hi :) Is the repo still maintained? a dependency update would be nice
